Rently/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rently.Models;

namespace Rently.Controllers
{
    [Authorize(Roles = RoleName.CanManageMovies)]
    public class RentalsController : Controller
    {
        public ActionResult New()
        {
            return View();
        }
    }
}

Rently/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
<!-- cut the main navbar in a different layout for ease of use called _navbar-->
@Html.Partial("_NavBar")
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Rently by Giuseppe Stirpe  &nbsp; &nbsp;
            <a href="https://ie.linkedin.com/in/giuseppe-stirpe-74227687 " 
               target="_blank" class="btn btn-info" role="button" aria-pressed="true">My Linkedin </a> </p>
    </footer>
</div>



@Scripts.Render("~/bundles/lib")
@RenderSection("scripts", required: false)
</body>
</html>

Rently/Views/Shared/_NavBar.cshtml
@using Rently.Models
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink(" Rently", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @if (ViewContext.HttpContext.User.IsInRole("CanManageMovies"))
                {
                    <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                }

                <li>@Html.ActionLink("Movies", "Index", "Movies")</li>

                <!--hide the rental movie ony for admins-->

                @if (ViewContext.HttpContext.User.IsInRole("CanManageMovies"))
                {
                    <li>@Html.ActionLink("New Rental", "New", "Rentals")</li>
                }

                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
